import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter, Geo } from "next/font/google";
import Image from "next/image";
import Tab from "./components/Tab";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter({
	weight: "variable",
	variable: "--font-inter",
});
const geo = Geo({
	weight: "400",
	variable: "--font-geo",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${geo.variable} ${inter.className}`}>
				<div className="flex flex-col w-screen min-h-screen justify-center items-center gap-5 overflow-auto p-4">
					<Image
						src="/logo.svg"
						width={300}
						height={100}
						alt="CubeCode Logo"
						priority
					/>
					<div className="inter opacity-50 text-sm">
						Encode & Decode Secret Messages with Rubik's Cubes
					</div>
					<div className="flex flex-row gap-10">
						<Tab url="/decode" title="decode" color="green" />
						<Tab url="/encode" title="encode" color="red" />
						<Tab url="/solve" title="solve" color="blue" />
					</div>
					<div className="w-full max-w-4xl border-1 border-black/40 rounded-2xl py-8">
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
